language: node_js
node_js:
  - "7"
before_install: 
  - echo "Installing modules"
  - chmod +x .travis/push.sh
install: 
  - npm install
script: 
  - npm run-script build
  - echo "Build finished"
after_success:
  - .travis/push.sh