language: node_js
node_js:
  - "7"
before_install: 
  - echo "Installing modules"
  - chmod +x .travis/push.sh
install: 
  - npm install
script: 
  - npm run-script build
  - echo "Build finished"
deploy:
  provider: pages
  target-branch: master
  local-dir: docs
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master